version: '3.6'
services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "8080:8080"
    depends_on:
    - "timescale"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@timescale:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      #uncomment next line to set an admin secret
      #HASURA_GRAPHQL_ADMIN_SECRET: password
volumes:
  db_data: